version: '3.3'
services:
  mongodb:
    image: mongo:4.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    
